services:
  backend-1:
    build: .
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: production
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '125MB'
    restart: unless-stopped

  backend-2:
    build: .
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: production
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '125MB'
    restart: unless-stopped

  load-balancer:
    image: nginx:alpine
    container_name: bulletonrails_load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "9999:80"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
    restart: unless-stopped

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
