
server:
  port: 8080
  undertow:
    threads:
      io: 16
      worker: 200
    buffer-size: 1024
    direct-buffers: true
    max-http-post-size: 512KB
  compression:
    enabled: false

spring:
  main:
    lazy-initialization: false
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  mvc:
    async:
      request-timeout: 5000
  task:
    execution:
      pool:
        core-size: 50
        max-size: 200
        queue-capacity: 1000
    scheduling:
      pool:
        size: 8

logging:
  level:
    root: WARN
    com.bulletonrails: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    enabled-by-default: false
