
server:
  port: 8080
  undertow:
    threads:
      io: 16
      worker: 200
    buffer-size: 1024
    direct-buffers: true
    max-http-post-size: 512KB
  compression:
    enabled: false

spring:
  main:
    lazy-initialization: false
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  mvc:
    async:
      request-timeout: 2000
  task:
    execution:
      pool:
        core-size: 100
        max-size: 500
        queue-capacity: 2000
      thread-name-prefix: "virtual-"
    scheduling:
      pool:
        size: 16
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: WARN
    com.bulletonrails: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    enabled-by-default: false
