
server:
  port: 8080
  undertow:
    threads:
      io: 4
      worker: 20
    buffer-size: 1024
    direct-buffers: true
  compression:
    enabled: true
    min-response-size: 1024

spring:
  main:
    lazy-initialization: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  mvc:
    async:
      request-timeout: 5000

logging:
  level:
    root: WARN
    com.bulletonrails: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    enabled-by-default: false
